<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/Anova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Anova : it is analysis of variance

    --->Anova helps us compare multiple groups and chek whether their average values are significantly different from each other

In [98]:
from scipy.stats import f_oneway
method_a=[70,72,68,75,74]
method_b=[80,82,78,85,81]
method_c=[90,92,88,95,91]
#f_stat tells us whether the grps are significantly different from each other
f_stat,p_value=f_oneway(method_a,method_b,method_c)
print("f-statistic:",f_stat)
print("p-value:",p_value)
if p_value<0.05:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

f-statistic: 65.36111111111104
p-value: 3.5329531740237255e-07
Reject the null hypothesis

In [99]:
from scipy.stats import chisquare
observed = [20,10,5,5]
expected = [10,10,10,10]
chi_stat,p_value=chisquare(observed,expected)
print("chi-statistic:",chi_stat)
print("p-value:",p_value)
if p_value<0.05:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

chi-statistic: 15.0
p-value: 0.0018166489665723214
Reject the null hypothesis

In [100]:
from statsmodels.stats.proportion import proportions_ztest
sucess=[180,120]
samples=[500,500]
z_stat,p_value=proportions_ztest(sucess,samples)
print("z-statistic:",z_stat)
print("p-value:",p_value)
if p_value<0.05:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

z-statistic: 4.140393356054125
p-value: 3.4671076872696536e-05
Reject the null hypothesis

#Task

In [101]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [102]:
df = pd.read_excel("/content/drive/MyDrive/Datasets for datascience/flight_price.xlsx")
df.head()

       Airline Date_of_Journey    Source  ... Total_Stops Additional_Info  Price
0       IndiGo      24/03/2019  Banglore  ...    non-stop         No info   3897
1    Air India       1/05/2019   Kolkata  ...     2 stops         No info   7662
2  Jet Airways       9/06/2019     Delhi  ...     2 stops         No info  13882
3       IndiGo      12/05/2019   Kolkata  ...      1 stop         No info   6218
4       IndiGo      01/03/2019  Banglore  ...      1 stop         No info  13302

[5 rows x 11 columns]

In [103]:
df['Date_of_Journey']=pd.to_datetime(df['Date_of_Journey'],format="%d/%m/%Y")
df['Journey_Day']=df['Date_of_Journey'].dt.day
df['Journey_Month']=df['Date_of_Journey'].dt.month
df['Journey_Year']=df['Date_of_Journey'].dt.year

In [104]:
df.head()

       Airline Date_of_Journey  ... Journey_Month Journey_Year
0       IndiGo      2019-03-24  ...             3         2019
1    Air India      2019-05-01  ...             5         2019
2  Jet Airways      2019-06-09  ...             6         2019
3       IndiGo      2019-05-12  ...             5         2019
4       IndiGo      2019-03-01  ...             3         2019

[5 rows x 14 columns]

In [105]:
df['Dep_Time']=pd.to_datetime(df['Dep_Time'])
df['dept_hour']=df['Dep_Time'].dt.hour
df['dept_min']=df['Dep_Time'].dt.minute
df.head()

/tmp/ipykernel_4428/718532931.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dep_Time']=pd.to_datetime(df['Dep_Time'])

       Airline Date_of_Journey    Source  ... Journey_Year dept_hour dept_min
0       IndiGo      2019-03-24  Banglore  ...         2019        22       20
1    Air India      2019-05-01   Kolkata  ...         2019         5       50
2  Jet Airways      2019-06-09     Delhi  ...         2019         9       25
3       IndiGo      2019-05-12   Kolkata  ...         2019        18        5
4       IndiGo      2019-03-01  Banglore  ...         2019        16       50

[5 rows x 16 columns]

In [106]:
df['Total_Stops']=df['Total_Stops'].replace({
    'non-stop':0,
    '1 stop':1,
    '2 stops':2,
    '3 stops':3,
    '4 stops':4
})
df.head()

/tmp/ipykernel_4428/3060211695.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Total_Stops']=df['Total_Stops'].replace({

       Airline Date_of_Journey    Source  ... Journey_Year dept_hour dept_min
0       IndiGo      2019-03-24  Banglore  ...         2019        22       20
1    Air India      2019-05-01   Kolkata  ...         2019         5       50
2  Jet Airways      2019-06-09     Delhi  ...         2019         9       25
3       IndiGo      2019-05-12   Kolkata  ...         2019        18        5
4       IndiGo      2019-03-01  Banglore  ...         2019        16       50

[5 rows x 16 columns]

In [107]:
df

           Airline Date_of_Journey    Source  ... Journey_Year dept_hour dept_min
0           IndiGo      2019-03-24  Banglore  ...         2019        22       20
1        Air India      2019-05-01   Kolkata  ...         2019         5       50
2      Jet Airways      2019-06-09     Delhi  ...         2019         9       25
3           IndiGo      2019-05-12   Kolkata  ...         2019        18        5
4           IndiGo      2019-03-01  Banglore  ...         2019        16       50
...            ...             ...       ...  ...          ...       ...      ...
10678     Air Asia      2019-04-09   Kolkata  ...         2019        19       55
10679    Air India      2019-04-27   Kolkata  ...         2019        20       45
10680  Jet Airways      2019-04-27  Banglore  ...         2019         8       20
10681      Vistara      2019-03-01  Banglore  ...         2019        11       30
10682    Air India      2019-05-09     Delhi  ...         2019        10       55

[10683 rows x 16 columns]

In [108]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['Airline']=encoder.fit_transform(df['Airline'])
df['Source']=encoder.fit_transform(df['Source'])
df['Destination']=encoder.fit_transform(df['Destination'])

In [109]:
df

       Airline Date_of_Journey  Source  ...  Journey_Year dept_hour dept_min
0            3      2019-03-24       0  ...          2019        22       20
1            1      2019-05-01       3  ...          2019         5       50
2            4      2019-06-09       2  ...          2019         9       25
3            3      2019-05-12       3  ...          2019        18        5
4            3      2019-03-01       0  ...          2019        16       50
...        ...             ...     ...  ...           ...       ...      ...
10678        0      2019-04-09       3  ...          2019        19       55
10679        1      2019-04-27       3  ...          2019        20       45
10680        4      2019-04-27       0  ...          2019         8       20
10681       10      2019-03-01       0  ...          2019        11       30
10682        1      2019-05-09       2  ...          2019        10       55

[10683 rows x 16 columns]

In [110]:
#using one hot encoder

In [111]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
encoder=OneHotEncoder(sparse_output=False)
encoded_cols=encoder.fit_transform(df[['Airline','Source','Destination']])
feature_names=encoder.get_feature_names_out(['Airline','Source','Destination'])
encoded_df=pd.DataFrame(encoded_cols,columns=feature_names,index=df.index)
df=pd.concat([df.drop(['Airline','Source','Destination'],axis=1),encoded_df],axis=1)
df

      Date_of_Journey                  Route  ... Destination_4 Destination_5
0          2019-03-24              BLR → DEL  ...           0.0           1.0
1          2019-05-01  CCU → IXR → BBI → BLR  ...           0.0           0.0
2          2019-06-09  DEL → LKO → BOM → COK  ...           0.0           0.0
3          2019-05-12        CCU → NAG → BLR  ...           0.0           0.0
4          2019-03-01        BLR → NAG → DEL  ...           0.0           1.0
...               ...                    ...  ...           ...           ...
10678      2019-04-09              CCU → BLR  ...           0.0           0.0
10679      2019-04-27              CCU → BLR  ...           0.0           0.0
10680      2019-04-27              BLR → DEL  ...           0.0           0.0
10681      2019-03-01              BLR → DEL  ...           0.0           1.0
10682      2019-05-09  DEL → GOI → BOM → COK  ...           0.0           0.0

[10683 rows x 36 columns]