<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/BaggingClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

In [16]:
df=pd.read_csv("/content/drive/MyDrive/Datasets for datascience/tips_classification.csv")
df

     total_bill   tip     sex smoker   day    time  size  tip_category
0         16.99  1.01  Female     No   Sun  Dinner     2             0
1         10.34  1.66    Male     No   Sun  Dinner     3             0
2         21.01  3.50    Male     No   Sun  Dinner     3             1
3         23.68  3.31    Male     No   Sun  Dinner     2             1
4         24.59  3.61  Female     No   Sun  Dinner     4             1
..          ...   ...     ...    ...   ...     ...   ...           ...
239       29.03  5.92    Male     No   Sat  Dinner     3             1
240       27.18  2.00  Female    Yes   Sat  Dinner     2             0
241       22.67  2.00    Male    Yes   Sat  Dinner     2             0
242       17.82  1.75    Male     No   Sat  Dinner     2             0
243       18.78  3.00  Female     No  Thur  Dinner     2             1

[244 rows x 8 columns]

In [17]:
df.head()

   total_bill   tip     sex smoker  day    time  size  tip_category
0       16.99  1.01  Female     No  Sun  Dinner     2             0
1       10.34  1.66    Male     No  Sun  Dinner     3             0
2       21.01  3.50    Male     No  Sun  Dinner     3             1
3       23.68  3.31    Male     No  Sun  Dinner     2             1
4       24.59  3.61  Female     No  Sun  Dinner     4             1

In [18]:
df.isnull().sum()

total_bill      0
tip             0
sex             0
smoker          0
day             0
time            0
size            0
tip_category    0
dtype: int64

In [19]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [20]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'tip_category'],
      dtype='object')

In [21]:
X=df.drop("tip_category", axis=1)
Y=df["tip_category"]

In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X["sex"]=le.fit_transform(X["sex"])
X["smoker"]=le.fit_transform(X["smoker"])
X["day"]=le.fit_transform(X["day"])
X["time"]=le.fit_transform(X["time"])

In [ ]:
X

In [ ]:
Y

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [26]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42)

In [27]:
from sklearn.ensemble import BaggingClassifier
bag_model=BaggingClassifier(
    estimator=dt,
    n_estimators=100,
    max_samples=0.8,
    bootstrap=True,
    random_state=42
)

In [28]:
bag_model.fit(X_train,Y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(random_state=42),
                  max_samples=0.8, n_estimators=100, random_state=42)

In [29]:
y_pred=bag_model.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(Y_test,y_pred)
print("accuracy of this model is",acc)

accuracy of this model is 0.9795918367346939