<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Ceaning
--> data cleaning is the process of detecting and fixing the missing values

In [ ]:
# raw data
# initial eda
# data cleaning
# feature engineering
# model
# duplicate records,incorrect data types,inconsistent formats
#step-1 handling missing values
#srep-2 remove duplicate records
#step-3 correcting data types
#step-4 handling outliers
#step-5 standardizing text values, rename

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Datasets for datascience/student_data_cleaning (1).csv")
df

  Student Name    Age          City  Marks   Join Date
0         Ram    20.0           HYD   85.0  2024-01-10
1         Ravi    NaN     Hyderabad   90.0  2024-02-15
2        Kumar   22.0           hyd    NaN  2024/03/20
3         Ram    20.0           HYD   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0           HYD   88.0  2024-05-01

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student Name  5 non-null      object
 1   Age           5 non-null      float64
 2   City          6 non-null      object
 3   Marks         5 non-null      float64
 4   Join Date     6 non-null      object
dtypes: float64(2), object(3)
memory usage: 372.0+ bytes

In [ ]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())
df

  Student Name    Age          City  Marks   Join Date
0         Ram    20.0           HYD   85.0  2024-01-10
1         Ravi   46.6     Hyderabad   90.0  2024-02-15
2        Kumar   22.0           hyd   88.6  2024/03/20
3         Ram    20.0           HYD   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0           HYD   88.0  2024-05-01

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df

  Student Name    Age          City  Marks   Join Date
0         Ram    20.0           HYD   85.0  2024-01-10
1         Ravi   46.6     Hyderabad   90.0  2024-02-15
2        Kumar   22.0           hyd   88.6  2024/03/20
3         Ram    20.0           HYD   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0           HYD   88.0  2024-05-01

In [ ]:
df["City"]=df["City"].replace(
    {
        "HYD":"Hyderabad",
        "hyd":"Hyderabad"
    }
)
df

  Student Name    Age          City  Marks   Join Date
0         Ram    20.0     Hyderabad   85.0  2024-01-10
1         Ravi   46.6     Hyderabad   90.0  2024-02-15
2        Kumar   22.0     Hyderabad   88.6  2024/03/20
3         Ram    20.0     Hyderabad   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0     Hyderabad   88.0  2024-05-01

In [ ]:
df.columns=(
    df.columns.str.lower().str.replace(" ","_")
)
df

  student_name    age          city  marks   join_date
0         Ram    20.0     Hyderabad   85.0  2024-01-10
1         Ravi   46.6     Hyderabad   90.0  2024-02-15
2        Kumar   22.0     Hyderabad   88.6  2024/03/20
3         Ram    20.0     Hyderabad   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0     Hyderabad   88.0  2024-05-01

In [ ]:
df["join_date"]=pd.to_datetime(
    df["join_date"],
    format="mixed"
)
df

  student_name    age          city  marks  join_date
0         Ram    20.0     Hyderabad   85.0 2024-01-10
1         Ravi   46.6     Hyderabad   90.0 2024-02-15
2        Kumar   22.0     Hyderabad   88.6 2024-03-20
3         Ram    20.0     Hyderabad   85.0 2024-01-10
4         John  150.0   Vijayawada    95.0 2024-04-25
5          NaN   21.0     Hyderabad   88.0 2024-05-01

#Feature Engineering : it is nothing but converting raw data into useful data for the model

#Task

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/employee_data (1).csv")
df

  Employee Name   Age Department  Salary   Join Date
0          Ram   25.0         IT   50000  2023-01-15
1          Ravi   NaN         it   60000  2023/02/20
2           NaN  30.0         HR   55000  2023-03-10
3         Kumar  28.0   Finance    65000  2023-04-05
4          Ram   25.0         IT   50000  2023-01-15

In [ ]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["Employee Name"]=df["Employee Name"].fillna("Unknown")

In [ ]:
df.duplicated().sum()
df=df.drop_duplicates()
df.head()

  Employee Name   Age Department  Salary   Join Date
0          Ram   25.0         IT   50000  2023-01-15
1          Ravi  27.0         it   60000  2023/02/20
2       Unknown  30.0         HR   55000  2023-03-10
3         Kumar  28.0   Finance    65000  2023-04-05
4          Ram   25.0         IT   50000  2023-01-15

In [ ]:
df["Employee Name"]=df["Employee Name"].str.strip()
df["Department"]=df["Department"].str.strip()

In [ ]:
df["Department"]=df["Department"].replace(
    {
        "IT":"Information Technology",
        "it":"Information Technology"
    }
)
df

  Employee Name   Age              Department  Salary   Join Date
0           Ram  25.0  Information Technology   50000  2023-01-15
1          Ravi  27.0  Information Technology   60000  2023/02/20
2       Unknown  30.0                      HR   55000  2023-03-10
3         Kumar  28.0                 Finance   65000  2023-04-05
4           Ram  25.0  Information Technology   50000  2023-01-15

In [ ]:
df.columns=(
    df.columns.str.lower().str.replace(" ","_")
)
df

  employee_name   age              department  salary   join_date
0           Ram  25.0  Information Technology   50000  2023-01-15
1          Ravi  27.0  Information Technology   60000  2023/02/20
2       Unknown  30.0                      HR   55000  2023-03-10
3         Kumar  28.0                 Finance   65000  2023-04-05
4           Ram  25.0  Information Technology   50000  2023-01-15

In [ ]:
df['join_date'] = pd.to_datetime(df['join_date'], format='mixed')
print(df['join_date'].dtype)

datetime64[ns]

In [ ]:
print(df['join_date'])

0   2023-01-15
1   2023-02-20
2   2023-03-10
3   2023-04-05
4   2023-01-15
Name: join_date, dtype: datetime64[ns]