<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/date_time_handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**data time handling** is the process of converting date and time into a format that computers can uunderstand

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Datasets for datascience/transaction_data (1).csv")
df

  customer_name transaction_date transaction_time transaction_datetime  amount
0      Santhosh       2024-01-15         09:30:45  2024-01-15 09:30:45    1000
1          Raju       2024-03-22         14:15:20  2024-03-22 14:15:20    2500
2         Kiran       2024-06-10         18:45:10  2024-06-10 18:45:10    1800
3        Suresh       2024-09-05         11:20:35  2024-09-05 11:20:35    3200
4       Lakshmi       2024-12-18         22:10:05  2024-12-18 22:10:05    1500

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_name         5 non-null      object
 1   transaction_date      5 non-null      object
 2   transaction_time      5 non-null      object
 3   transaction_datetime  5 non-null      object
 4   amount                5 non-null      int64
dtypes: int64(1), object(4)
memory usage: 332.0+ bytes

In [ ]:
df["transaction_date"]=pd.to_datetime(df["transaction_date"])
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_name         5 non-null      object
 1   transaction_date      5 non-null      datetime64[ns]
 2   transaction_time      5 non-null      object
 3   transaction_datetime  5 non-null      object
 4   amount                5 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 332.0+ bytes

In [ ]:
df["transaction_time"]=pd.to_datetime(df["transaction_time"])
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_name         5 non-null      object
 1   transaction_date      5 non-null      datetime64[ns]
 2   transaction_time      5 non-null      datetime64[ns]
 3   transaction_datetime  5 non-null      object
 4   amount                5 non-null      int64
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 332.0+ bytes

/tmp/ipykernel_2339/2772445953.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["transaction_time"]=pd.to_datetime(df["transaction_time"])

In [ ]:
df["transaction_datetime"]=pd.to_datetime(df["transaction_datetime"])
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_name         5 non-null      object
 1   transaction_date      5 non-null      datetime64[ns]
 2   transaction_time      5 non-null      datetime64[ns]
 3   transaction_datetime  5 non-null      datetime64[ns]
 4   amount                5 non-null      int64
dtypes: datetime64[ns](3), int64(1), object(1)
memory usage: 332.0+ bytes

In [ ]:
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500

In [ ]:
df["year"]=df["transaction_date"].dt.year
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount,year
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000,2024
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500,2024
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800,2024
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200,2024
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500,2024

In [ ]:
df["month"]=df["transaction_date"].dt.month
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount,year,month
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000,2024,1
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500,2024,3
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800,2024,6
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200,2024,9
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500,2024,12

In [ ]:
df["day"]=df["transaction_date"].dt.day
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount,year,month,day
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000,2024,1,15
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500,2024,3,22
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800,2024,6,10
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200,2024,9,5
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500,2024,12,18

In [ ]:
df["month_name"]=df["transaction_date"].dt.month_name()
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount,year,month,day,month_name
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000,2024,1,15,January
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500,2024,3,22,March
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800,2024,6,10,June
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200,2024,9,5,September
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500,2024,12,18,December

In [ ]:
df["day_name"]=df["transaction_date"].dt.day_name()
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount,year,month,day,month_name,day_name
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000,2024,1,15,January,Monday
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500,2024,3,22,March,Friday
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800,2024,6,10,June,Monday
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200,2024,9,5,September,Thursday
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500,2024,12,18,December,Wednesday

#Extract quarter

In [ ]:
df["quarter"]=df["transaction_date"].dt.quarter
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount,year,month,day,month_name,day_name,quarter
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000,2024,1,15,January,Monday,1
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500,2024,3,22,March,Friday,1
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800,2024,6,10,June,Monday,2
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200,2024,9,5,September,Thursday,3
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500,2024,12,18,December,Wednesday,4

In [ ]:
df["hour"]=df["transaction_datetime"].dt.hour
df["minutes"]=df["transaction_datetime"].dt.minute
df["seconds"]=df["transaction_datetime"].dt.second
df["date"]=df["transaction_datetime"].dt.date
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount,year,month,day,month_name,day_name,quarter,hour,minutes,seconds,date
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000,2024,1,15,January,Monday,1,9,30,45,2024-01-15
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500,2024,3,22,March,Friday,1,14,15,20,2024-03-22
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800,2024,6,10,June,Monday,2,18,45,10,2024-06-10
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200,2024,9,5,September,Thursday,3,11,20,35,2024-09-05
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500,2024,12,18,December,Wednesday,4,22,10,5,2024-12-18

#**Task** six

In [ ]:
df=pd.read_csv("/content/employee_attendance (1).csv")
df

  employee_name  login_date login_time  working_hours
0          Ravi  2024-02-10   08:45:30              8
1         Priya  2024-03-15   09:10:15              9
2       Karthik  2024-05-20   08:55:45              8
3        Anjali  2024-07-08   09:25:10              7
4        Vikram  2024-11-25   08:30:20              9

In [ ]:
import pandas as pd

In [ ]:
df["login_date"]=pd.to_datetime(df["login_date"])
print(df["login_date"])

0   2024-02-10
1   2024-03-15
2   2024-05-20
3   2024-07-08
4   2024-11-25
Name: login_date, dtype: datetime64[ns]

In [ ]:
df["year"]=df["login_date"].dt.year
df["month"]=df["login_date"].dt.month
df["day"]=df["login_date"].dt.day
df
print(df[["year","month","day"]])

   year  month  day
0  2024      2   10
1  2024      3   15
2  2024      5   20
3  2024      7    8
4  2024     11   25

In [ ]:
df["month_name"]=df["login_date"].dt.month_name()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name
0,Ravi,2024-02-10,08:45:30,8,2024,2,10,February
1,Priya,2024-03-15,09:10:15,9,2024,3,15,March
2,Karthik,2024-05-20,08:55:45,8,2024,5,20,May
3,Anjali,2024-07-08,09:25:10,7,2024,7,8,July
4,Vikram,2024-11-25,08:30:20,9,2024,11,25,November

In [ ]:
df["day_name"]=df["login_date"].dt.day_name()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name,day_name
0,Ravi,2024-02-10,08:45:30,8,2024,2,10,February,Saturday
1,Priya,2024-03-15,09:10:15,9,2024,3,15,March,Friday
2,Karthik,2024-05-20,08:55:45,8,2024,5,20,May,Monday
3,Anjali,2024-07-08,09:25:10,7,2024,7,8,July,Monday
4,Vikram,2024-11-25,08:30:20,9,2024,11,25,November,Monday

In [ ]:
df["login_time"]=pd.to_datetime(df["login_time"])
df["hour"]=df["login_time"].dt.hour
df["minutes"]=df["login_time"].dt.minute
df["seconds"]=df["login_time"].dt.second
df
print(df[["hour","minutes","seconds"]])

   hour  minutes  seconds
0     8       45       30
1     9       10       15
2     8       55       45
3     9       25       10
4     8       30       20

In [ ]:
earliest_date=df["login_date"].min()
print(earliest_date)

2024-02-10 00:00:00

In [ ]:
largest_date=df["login_date"].max()
print(largest_date)

2024-11-25 00:00:00

In [ ]:
max_hours_employee=df[df["working_hours"]==df["working_hours"].max()]
print(max_hours_employee)

  employee_name login_date          login_time  working_hours  year  month  \
1         Priya 2024-03-15 2026-05-30 09:10:15              9  2024      3
4        Vikram 2024-11-25 2026-05-30 08:30:20              9  2024     11

   day month_name day_name  hour  minutes  seconds
1   15      March   Friday     9       10       15
4   25   November   Monday     8       30       20