<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/Groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Groupby** : it enables catogary analysis instead of row by row analysis

In [7]:
import pandas as pd

In [8]:
df=pd.read_csv("/content/drive/MyDrive/Datasets for datascience/weather_by_cities.csv")

In [9]:
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [21]:
g=df.groupby("city")

In [16]:
for city,city_df in g:
  print(city)
  print(city_df)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [12]:
g.get_group("mumbai")

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [13]:
df.columns

Index(['day', 'city', 'temperature', 'windspeed', 'event'], dtype='object')

In [17]:
df.groupby("city")["temperature"].max()

city
mumbai      92
new york    36
paris       54
Name: temperature, dtype: int64

In [19]:
#find the avg wind speed per city
df.groupby("city")["windspeed"].mean()

city
mumbai       9.25
new york     8.00
paris       12.75
Name: windspeed, dtype: float64

#**Task Four**

In [22]:
#find average wind speed per city
df.groupby("city")["windspeed"].sum()

city
mumbai      37
new york    32
paris       51
Name: windspeed, dtype: int64

In [26]:
#find the highest wind speed for each city
df.groupby("city")["windspeed"].max()

city
mumbai      15
new york    12
paris       20
Name: windspeed, dtype: int64