<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#pandas

In [5]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd
import numpy as np

#series

In [7]:
#series
arr=np.array([10,20,30,40,50])
s=pd.Series(arr)
print(s)
print(s[0])

0    10
1    20
2    30
3    40
4    50
dtype: int64
10

In [8]:
marks=pd.Series(
    [10,20,30],
    index=["math","phy","chem"]
)
print(marks)
print(marks["math"])
#shape: it gives rows and colomns👇
print(marks.shape)
#size:it gives no. of elements👇
print(marks.size)
print(marks.ndim)
print(marks.dtype)
print(marks.index)
print(marks.values)

math    10
phy     20
chem    30
dtype: int64
10
(3,)
3
1
int64
Index(['math', 'phy', 'chem'], dtype='object')
[10 20 30]

#applyling operations using loops👇👇

In [9]:
#=> 2,4,68,14
numbers=[1,2,34,7]
result=[]
for i in numbers:
  result.append(i*2)
print(result)

[2, 4, 68, 14]

#***vectorized*** ***operation*** means applying one operation to all elements automatically without writing loops👇👇

In [10]:
numbers=[1,2,34,7]
arr=np.array(numbers)
print(arr*2)

[ 2  4 68 14]

#if i want to know the missing values.i will use isnull() method

In [11]:
data=pd.Series([10,20,30,40,np.nan,50])
# [10,20,30,40,np.nan,50]
print(data.isnull())
print(data.fillna(0))

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool
0    10.0
1    20.0
2    30.0
3    40.0
4     0.0
5    50.0
dtype: float64

#***DataFrame***

In [12]:
#dictionaries={}
data={
    "name": ["st1","st2","st3","st4"],
    "marks": [10,20,30,40],
    "city": ["c1","c2","c3","c4"]
}
df=pd.DataFrame(data)
print(df)
print(df.shape)
print(df.size)
print(df.columns)
print(df.index)
print(df.ndim)
print(df.info)

  name  marks city
0  st1     10   c1
1  st2     20   c2
2  st3     30   c3
3  st4     40   c4
(4, 3)
12
Index(['name', 'marks', 'city'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
2
<bound method DataFrame.info of   name  marks city
0  st1     10   c1
1  st2     20   c2
2  st3     30   c3
3  st4     40   c4>

#***create*** a new column

In [13]:
df["grade"]=["b","b","a","a"]
print(df)

  name  marks city grade
0  st1     10   c1     b
1  st2     20   c2     b
2  st3     30   c3     a
3  st4     40   c4     a

#***updating*** a column

In [14]:
df["marks"]=df["marks"]+20
print(df)

  name  marks city grade
0  st1     30   c1     b
1  st2     40   c2     b
2  st3     50   c3     a
3  st4     60   c4     a

In [15]:
df.drop("city",axis=1)

  name  marks grade
0  st1     30     b
1  st2     40     b
2  st3     50     a
3  st4     60     a

In [16]:
import pandas as pd

#axis=0=>removing rows
#axis=1=>removing columns

#reading ***csv*** file

In [17]:
import pandas as pd

In [26]:
df=pd.read_csv("/content/drive/MyDrive/Datasets for datascience/student_dataset_20rows.csv")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [28]:
df.drop("City",axis=1,inplace=True)
print(df)

    Student_ID     Name  Age            Course  Marks
0          101      Ram   25            Pandas     90
1          102     Ravi   23             NumPy     81
2          103     Sita   21            Python     80
3          104    Kiran   21      Data Science     98
4          105      Anu   20            Pandas     70
5          106    Rahul   22               SQL     82
6          107    Sneha   25     Deep Learning     79
7          108    Arjun   22  Machine Learning     70
8          109    Pooja   20            Python     95
9          110   Vikram   20               SQL     72
10         111    Divya   23     Deep Learning     94
11         112     Ajay   21            Python     84
12         113  Keerthi   21             NumPy     74
13         114   Nikhil   22     Deep Learning     99
14         115    Meena   23                AI     81
15         116      Sai   25            Pandas     97
16         117  Lavanya   20                AI     72
17         118    Rohit   23            Python     70
18         119     Teja   25  Machine Learning     90
19         120    Priya   22               SQL     78

In [29]:
df

    Student_ID     Name  Age            Course  Marks
0          101      Ram   25            Pandas     90
1          102     Ravi   23             NumPy     81
2          103     Sita   21            Python     80
3          104    Kiran   21      Data Science     98
4          105      Anu   20            Pandas     70
5          106    Rahul   22               SQL     82
6          107    Sneha   25     Deep Learning     79
7          108    Arjun   22  Machine Learning     70
8          109    Pooja   20            Python     95
9          110   Vikram   20               SQL     72
10         111    Divya   23     Deep Learning     94
11         112     Ajay   21            Python     84
12         113  Keerthi   21             NumPy     74
13         114   Nikhil   22     Deep Learning     99
14         115    Meena   23                AI     81
15         116      Sai   25            Pandas     97
16         117  Lavanya   20                AI     72
17         118    Rohit   23            Python     70
18         119     Teja   25  Machine Learning     90
19         120    Priya   22               SQL     78

In [30]:
df.drop(0,axis=0,inplace=True)
print(df)

    Student_ID     Name  Age            Course  Marks
1          102     Ravi   23             NumPy     81
2          103     Sita   21            Python     80
3          104    Kiran   21      Data Science     98
4          105      Anu   20            Pandas     70
5          106    Rahul   22               SQL     82
6          107    Sneha   25     Deep Learning     79
7          108    Arjun   22  Machine Learning     70
8          109    Pooja   20            Python     95
9          110   Vikram   20               SQL     72
10         111    Divya   23     Deep Learning     94
11         112     Ajay   21            Python     84
12         113  Keerthi   21             NumPy     74
13         114   Nikhil   22     Deep Learning     99
14         115    Meena   23                AI     81
15         116      Sai   25            Pandas     97
16         117  Lavanya   20                AI     72
17         118    Rohit   23            Python     70
18         119     Teja   25  Machine Learning     90
19         120    Priya   22               SQL     78

#reading ***json*** file

In [19]:
df=pd.read_json("/content/drive/MyDrive/Datasets for datascience/student_dataset_20rows.json")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

#reading ***excel*** file

In [20]:
df=pd.read_excel("/content/drive/MyDrive/Datasets for datascience/student_dataset_20rows.xlsx")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [31]:
import pandas as pd

In [32]:
df=pd.read_csv("/content/drive/MyDrive/Datasets for datascience/student_dataset_20rows.csv")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

#selecting columns

In [33]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'City'], dtype='object')

In [35]:
df["Marks"]

0     90
1     81
2     80
3     98
4     70
5     82
6     79
7     70
8     95
9     72
10    94
11    84
12    74
13    99
14    81
15    97
16    72
17    70
18    90
19    78
Name: Marks, dtype: int64

In [40]:
df["Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [39]:
df["City"]

0      Vijayawada
1       Hyderabad
2         Chennai
3       Bangalore
4          Mumbai
5           Delhi
6            Pune
7         Kolkata
8           Vizag
9        Tirupati
10       Warangal
11         Guntur
12        Nellore
13         Kadapa
14        Kurnool
15         Ongole
16    Rajahmundry
17          Eluru
18        Khammam
19      Nizamabad
Name: City, dtype: object

In [38]:
df[["Name","Age"]]

       Name  Age
0       Ram   25
1      Ravi   23
2      Sita   21
3     Kiran   21
4       Anu   20
5     Rahul   22
6     Sneha   25
7     Arjun   22
8     Pooja   20
9    Vikram   20
10    Divya   23
11     Ajay   21
12  Keerthi   21
13   Nikhil   22
14    Meena   23
15      Sai   25
16  Lavanya   20
17    Rohit   23
18     Teja   25
19    Priya   22

In [36]:
df[["Name","Age","City"]]

       Name  Age         City
0       Ram   25   Vijayawada
1      Ravi   23    Hyderabad
2      Sita   21      Chennai
3     Kiran   21    Bangalore
4       Anu   20       Mumbai
5     Rahul   22        Delhi
6     Sneha   25         Pune
7     Arjun   22      Kolkata
8     Pooja   20        Vizag
9    Vikram   20     Tirupati
10    Divya   23     Warangal
11     Ajay   21       Guntur
12  Keerthi   21      Nellore
13   Nikhil   22       Kadapa
14    Meena   23      Kurnool
15      Sai   25       Ongole
16  Lavanya   20  Rajahmundry
17    Rohit   23        Eluru
18     Teja   25      Khammam
19    Priya   22    Nizamabad

#Selecting rows using ***iloc*** function
#***iloc*** = integer location

In [41]:
df.iloc[0]

Student_ID           101
Name                 Ram
Age                   25
Course            Pandas
Marks                 90
City          Vijayawada
Name: 0, dtype: object

In [42]:
df.iloc[0:3]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

#Selecting specific rows and columns

In [43]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [44]:
#Syntax
# df.iloc[rowselecton,columnselection]
df.iloc[0:3,0:3]

   Student_ID  Name  Age
0         101   Ram   25
1         102  Ravi   23
2         103  Sita   21

In [45]:
df.iloc[0,0:3]

Student_ID    101
Name          Ram
Age            25
Name: 0, dtype: object

In [48]:
df.iloc[[0,1,4,3]]

   Student_ID   Name  Age        Course  Marks        City
0         101    Ram   25        Pandas     90  Vijayawada
1         102   Ravi   23         NumPy     81   Hyderabad
4         105    Anu   20        Pandas     70      Mumbai
3         104  Kiran   21  Data Science     98   Bangalore

suppose if i am accesing multiple rows


*   in **iloc** function suppose my range is 0 to n-->i will get output as 0 to n-1
*   in **loc** function suppose my range is 0 to n-->i will get output as 0 to n

#in loc function if you want to acces columns you have to use column names

In [52]:
df.loc[0:2]
#include last range

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

In [53]:
df.iloc[0:2]
#exclude last range

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad

In [54]:
df.loc[:,"Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [57]:
df.loc[:,["Name","Marks"]]

       Name  Marks
0       Ram     90
1      Ravi     81
2      Sita     80
3     Kiran     98
4       Anu     70
5     Rahul     82
6     Sneha     79
7     Arjun     70
8     Pooja     95
9    Vikram     72
10    Divya     94
11     Ajay     84
12  Keerthi     74
13   Nikhil     99
14    Meena     81
15      Sai     97
16  Lavanya     72
17    Rohit     70
18     Teja     90
19    Priya     78

In [58]:
df.loc[5:8,["Name","Age","City"]]

    Name  Age     City
5  Rahul   22    Delhi
6  Sneha   25     Pune
7  Arjun   22  Kolkata
8  Pooja   20    Vizag

In [59]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'City'], dtype='object')

#Main Task 1
Task one

In [60]:
df["Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [64]:
df.loc[:,"Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [66]:
df.iloc[:,1]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

Task Two

In [67]:
df[["Name","City"]]

       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad

In [68]:
df.loc[:,["Name","City"]]

       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad

In [69]:
df.iloc[:,[1,5]]

       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad

Task Three

In [70]:
df.loc[0:2]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

In [71]:
df.iloc[0:3]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

Task Four

In [72]:
df.loc[0:1,["Student_ID","Name"]]

   Student_ID  Name
0         101   Ram
1         102  Ravi

In [73]:
df.iloc[0:2,0:2]

   Student_ID  Name
0         101   Ram
1         102  Ravi

Task five

In [74]:
df.loc[:,"Marks"]

0     90
1     81
2     80
3     98
4     70
5     82
6     79
7     70
8     95
9     72
10    94
11    84
12    74
13    99
14    81
15    97
16    72
17    70
18    90
19    78
Name: Marks, dtype: int64

In [76]:
df.iloc[:,4]

0     90
1     81
2     80
3     98
4     70
5     82
6     79
7     70
8     95
9     72
10    94
11    84
12    74
13    99
14    81
15    97
16    72
17    70
18    90
19    78
Name: Marks, dtype: int64

#Filtering

In [78]:
#filter marks greater than 80
df[df["Marks"]>80]

    Student_ID    Name  Age            Course  Marks        City
0          101     Ram   25            Pandas     90  Vijayawada
1          102    Ravi   23             NumPy     81   Hyderabad
3          104   Kiran   21      Data Science     98   Bangalore
5          106   Rahul   22               SQL     82       Delhi
8          109   Pooja   20            Python     95       Vizag
10         111   Divya   23     Deep Learning     94    Warangal
11         112    Ajay   21            Python     84      Guntur
13         114  Nikhil   22     Deep Learning     99      Kadapa
14         115   Meena   23                AI     81     Kurnool
15         116     Sai   25            Pandas     97      Ongole
18         119    Teja   25  Machine Learning     90     Khammam

In [79]:
#marks lesser than 80
df[df["Marks"]<80]

    Student_ID     Name  Age            Course  Marks         City
4          105      Anu   20            Pandas     70       Mumbai
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
9          110   Vikram   20               SQL     72     Tirupati
12         113  Keerthi   21             NumPy     74      Nellore
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
19         120    Priya   22               SQL     78    Nizamabad

In [80]:
df[df["Age"]>=21]

    Student_ID     Name  Age            Course  Marks        City
0          101      Ram   25            Pandas     90  Vijayawada
1          102     Ravi   23             NumPy     81   Hyderabad
2          103     Sita   21            Python     80     Chennai
3          104    Kiran   21      Data Science     98   Bangalore
5          106    Rahul   22               SQL     82       Delhi
6          107    Sneha   25     Deep Learning     79        Pune
7          108    Arjun   22  Machine Learning     70     Kolkata
10         111    Divya   23     Deep Learning     94    Warangal
11         112     Ajay   21            Python     84      Guntur
12         113  Keerthi   21             NumPy     74     Nellore
13         114   Nikhil   22     Deep Learning     99      Kadapa
14         115    Meena   23                AI     81     Kurnool
15         116      Sai   25            Pandas     97      Ongole
17         118    Rohit   23            Python     70       Eluru
18         119     Teja   25  Machine Learning     90     Khammam
19         120    Priya   22               SQL     78   Nizamabad

In [89]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [83]:
df[df["City"]=="Vijayawada"]

   Student_ID Name  Age  Course  Marks        City
0         101  Ram   25  Pandas     90  Vijayawada

In [86]:
df[(df["Marks"]>80) & (df['Age']>=21)]

    Student_ID    Name  Age            Course  Marks        City
0          101     Ram   25            Pandas     90  Vijayawada
1          102    Ravi   23             NumPy     81   Hyderabad
3          104   Kiran   21      Data Science     98   Bangalore
5          106   Rahul   22               SQL     82       Delhi
10         111   Divya   23     Deep Learning     94    Warangal
11         112    Ajay   21            Python     84      Guntur
13         114  Nikhil   22     Deep Learning     99      Kadapa
14         115   Meena   23                AI     81     Kurnool
15         116     Sai   25            Pandas     97      Ongole
18         119    Teja   25  Machine Learning     90     Khammam

In [88]:
df[(df["Marks"]>80) | (df['Age']>=21)]

    Student_ID     Name  Age            Course  Marks        City
0          101      Ram   25            Pandas     90  Vijayawada
1          102     Ravi   23             NumPy     81   Hyderabad
2          103     Sita   21            Python     80     Chennai
3          104    Kiran   21      Data Science     98   Bangalore
5          106    Rahul   22               SQL     82       Delhi
6          107    Sneha   25     Deep Learning     79        Pune
7          108    Arjun   22  Machine Learning     70     Kolkata
8          109    Pooja   20            Python     95       Vizag
10         111    Divya   23     Deep Learning     94    Warangal
11         112     Ajay   21            Python     84      Guntur
12         113  Keerthi   21             NumPy     74     Nellore
13         114   Nikhil   22     Deep Learning     99      Kadapa
14         115    Meena   23                AI     81     Kurnool
15         116      Sai   25            Pandas     97      Ongole
17         118    Rohit   23            Python     70       Eluru
18         119     Teja   25  Machine Learning     90     Khammam
19         120    Priya   22               SQL     78   Nizamabad

by using **loc** function

In [93]:
df.loc[df["Marks"]>80,["Name","Marks"]]

      Name  Marks
0      Ram     90
1     Ravi     81
3    Kiran     98
5    Rahul     82
8    Pooja     95
10   Divya     94
11    Ajay     84
13  Nikhil     99
14   Meena     81
15     Sai     97
18    Teja     90

#Main Task Two

In [104]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [99]:
df[df["Marks"]<70]

Empty DataFrame
Columns: [Student_ID, Name, Age, Course, Marks, City]
Index: []

In [105]:
df[df["City"]=="Bangalore"]

   Student_ID   Name  Age        Course  Marks       City
3         104  Kiran   21  Data Science     98  Bangalore

In [107]:
df[df["Age"]<30]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [102]:
df[(df["Marks"]>25) & (df['Age']>30)]

Empty DataFrame
Columns: [Student_ID, Name, Age, Course, Marks, City]
Index: []

In [108]:
df.loc[df["City"]=="Chennai",["Name","Age"]]

   Name  Age
2  Sita   21

#diff b/w loc and iloc
*   loc=>0:3=0,1,2,3(we use rows with index and columns with their names)

*   iloc=>0:3=0,1,2(we use rows and columns with index values)

#Sorting
* Sorting : arranging data in a paticular order

-->Usually ascending order,descending order

-->syntax : df.sort_values(by="column name")

In [111]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [113]:
df.sort_values(by="Marks") #Ascending order

    Student_ID     Name  Age            Course  Marks         City
7          108    Arjun   22  Machine Learning     70      Kolkata
4          105      Anu   20            Pandas     70       Mumbai
17         118    Rohit   23            Python     70        Eluru
9          110   Vikram   20               SQL     72     Tirupati
16         117  Lavanya   20                AI     72  Rajahmundry
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
6          107    Sneha   25     Deep Learning     79         Pune
2          103     Sita   21            Python     80      Chennai
1          102     Ravi   23             NumPy     81    Hyderabad
14         115    Meena   23                AI     81      Kurnool
5          106    Rahul   22               SQL     82        Delhi
11         112     Ajay   21            Python     84       Guntur
18         119     Teja   25  Machine Learning     90      Khammam
0          101      Ram   25            Pandas     90   Vijayawada
10         111    Divya   23     Deep Learning     94     Warangal
8          109    Pooja   20            Python     95        Vizag
15         116      Sai   25            Pandas     97       Ongole
3          104    Kiran   21      Data Science     98    Bangalore
13         114   Nikhil   22     Deep Learning     99       Kadapa

In [112]:
df.sort_values(by="Marks",ascending=False) #Descesnding order

    Student_ID     Name  Age            Course  Marks         City
13         114   Nikhil   22     Deep Learning     99       Kadapa
3          104    Kiran   21      Data Science     98    Bangalore
15         116      Sai   25            Pandas     97       Ongole
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal
18         119     Teja   25  Machine Learning     90      Khammam
0          101      Ram   25            Pandas     90   Vijayawada
11         112     Ajay   21            Python     84       Guntur
5          106    Rahul   22               SQL     82        Delhi
1          102     Ravi   23             NumPy     81    Hyderabad
14         115    Meena   23                AI     81      Kurnool
2          103     Sita   21            Python     80      Chennai
6          107    Sneha   25     Deep Learning     79         Pune
19         120    Priya   22               SQL     78    Nizamabad
12         113  Keerthi   21             NumPy     74      Nellore
9          110   Vikram   20               SQL     72     Tirupati
16         117  Lavanya   20                AI     72  Rajahmundry
7          108    Arjun   22  Machine Learning     70      Kolkata
4          105      Anu   20            Pandas     70       Mumbai
17         118    Rohit   23            Python     70        Eluru

In [114]:
df.sort_values(by="City")

    Student_ID     Name  Age            Course  Marks         City
3          104    Kiran   21      Data Science     98    Bangalore
2          103     Sita   21            Python     80      Chennai
5          106    Rahul   22               SQL     82        Delhi
17         118    Rohit   23            Python     70        Eluru
11         112     Ajay   21            Python     84       Guntur
1          102     Ravi   23             NumPy     81    Hyderabad
13         114   Nikhil   22     Deep Learning     99       Kadapa
18         119     Teja   25  Machine Learning     90      Khammam
7          108    Arjun   22  Machine Learning     70      Kolkata
14         115    Meena   23                AI     81      Kurnool
4          105      Anu   20            Pandas     70       Mumbai
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
15         116      Sai   25            Pandas     97       Ongole
6          107    Sneha   25     Deep Learning     79         Pune
16         117  Lavanya   20                AI     72  Rajahmundry
9          110   Vikram   20               SQL     72     Tirupati
0          101      Ram   25            Pandas     90   Vijayawada
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal

In [121]:
df.sort_values(by=["City","Marks"])

    Student_ID     Name  Age            Course  Marks         City
3          104    Kiran   21      Data Science     98    Bangalore
2          103     Sita   21            Python     80      Chennai
5          106    Rahul   22               SQL     82        Delhi
17         118    Rohit   23            Python     70        Eluru
11         112     Ajay   21            Python     84       Guntur
1          102     Ravi   23             NumPy     81    Hyderabad
13         114   Nikhil   22     Deep Learning     99       Kadapa
18         119     Teja   25  Machine Learning     90      Khammam
7          108    Arjun   22  Machine Learning     70      Kolkata
14         115    Meena   23                AI     81      Kurnool
4          105      Anu   20            Pandas     70       Mumbai
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
15         116      Sai   25            Pandas     97       Ongole
6          107    Sneha   25     Deep Learning     79         Pune
16         117  Lavanya   20                AI     72  Rajahmundry
9          110   Vikram   20               SQL     72     Tirupati
0          101      Ram   25            Pandas     90   Vijayawada
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal

#why values will be missing in datasets??


*   user forget to enter data
*   data entry mistakes
*   sensor issues
*   information not available

#**Imputation** : filling missing values in datasets by using some methods or logic

-->Mean

-->Median

-->Mode

In [ ]:
import seaborn as sns
df=sns.load_dataset("titanic")
df

In [ ]:
df.head()

In [ ]:
df.isnull()

In [127]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [130]:
df.shape

(891, 15)

In [131]:
df["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
df.columns

In [147]:
df["Age_Mean"]=df["age"].fillna(df["age"].mean())
print(df["Age_Mean"])

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age_Mean, Length: 891, dtype: float64

In [146]:
df[["Age_Mean","age"]]

      Age_Mean   age
0    22.000000  22.0
1    38.000000  38.0
2    26.000000  26.0
3    35.000000  35.0
4    35.000000  35.0
..         ...   ...
886  27.000000  27.0
887  19.000000  19.0
888  29.699118   NaN
889  26.000000  26.0
890  32.000000  32.0

[891 rows x 2 columns]

In [144]:
df["Age_Median"]=df["age"].fillna(df["age"].median())
print(df["Age_Median"])

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age_Median, Length: 891, dtype: float64

In [148]:
df[["Age_Median","age"]]

     Age_Median   age
0          22.0  22.0
1          38.0  38.0
2          26.0  26.0
3          35.0  35.0
4          35.0  35.0
..          ...   ...
886        27.0  27.0
887        19.0  19.0
888        28.0   NaN
889        26.0  26.0
890        32.0  32.0

[891 rows x 2 columns]

In [152]:
df["Age_Mode"]=df["age"].fillna(df["age"].mode())
print(df["Age_Mode"])

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age_Mode, Length: 891, dtype: float64

In [156]:
print(df["age"].mode())

0    29.699118
Name: age, dtype: float64

In [149]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Age_Mean,Age_Median,Age_Mode
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,22.000000,22.0,22.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,38.000000,38.0,38.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,26.000000,26.0,26.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,35.000000,35.0,35.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,35.000000,35.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,27.000000,27.0,27.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,19.000000,19.0,19.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,29.699118,28.0,24.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,26.000000,26.0,26.0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,32.000000,32.0,32.0

In [150]:
df["age"]=df["age"].fillna(df["age"].mean())

In [151]:
print(df["age"])

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64