<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/String_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
# # string processing in pandas means perfroming operations on text(string)
# # data stored in dataframe columns using pandas string functions
# cHevuri
# 1000,
# 50
# chevurisanthosh@gmail.com
# chevurisantosh@outlook.com
# "    santosh"

In [43]:
s = "   lahari"
#if we want to remove spaces we will use strip method
#lstrip it will remove spaces in left side
#rstrip it will remove spaces in right side only
#strip #it will remove spaces from both sides
print(s.strip())

lahari

In [62]:
df = pd.read_csv("/content/drive/MyDrive/Datasets for datascience/string_processing_dataset.csv")

In [66]:
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,startswithv,email_parts
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024,True,santhosh
1,RAJU KUMAR,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,False,RAJU
2,kiran reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024,False,kiran
3,SURESH BABU,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024,False,suresh
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024,False,lakshmi

In [65]:
df["email"] = df["email"].str.lower() #we are converting into the lower case
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,startswithv,email_parts
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024,True,santhosh
1,RAJU KUMAR,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,False,RAJU
2,kiran reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024,False,kiran
3,SURESH BABU,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024,False,suresh
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024,False,lakshmi

In [67]:
#convert cities into uppercase
df["city"] = df["city"].str.upper()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,startswithv,email_parts
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024,True,santhosh
1,RAJU KUMAR,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,False,RAJU
2,kiran reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024,False,kiran
3,SURESH BABU,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024,False,suresh
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024,False,lakshmi

In [68]:
#converting customer_name column into title
df["customer_name"] = df["customer_name"].str.title()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,startswithv,email_parts
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024,True,santhosh
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,False,RAJU
2,Kiran Reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024,False,kiran
3,Suresh Babu,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024,False,suresh
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024,False,lakshmi

In [ ]:
df["name_length"] = df["customer_name"].str.len()
df

In [ ]:
df

In [52]:
# regex = false tella pandas to treat the value as normal text and not as a special pattern

In [ ]:
df["purchase_amount"] = df["purchase_amount"].str.replace("Rs ", "", regex= False)
df

In [ ]:
df["purchase_amount"] = df["purchase_amount"].str.replace("$", "", regex= False)
df

In [ ]:
df["purchase_amount"] = df["purchase_amount"].str.replace(",", "", regex= False)
df

In [ ]:
df["is_mail"] = df["email"].str.contains("gmail")
df

In [ ]:
df["endswith"] = df["email"].str.endswith(".com")
df

In [ ]:
df

In [ ]:
df["email_parts"] = df["email"].str.split("@")
df

In [ ]:
df["startswithv"] = df["city"].str.startswith("V")
df

In [ ]:
df["email_parts"] = df["email"].str.split("@").str[0]
df

In [ ]:
df["vity_code"]=df["city"].str[:3]
df

In [86]:
df["is_numeric"]=df["phone"].astype(str).str.isnumeric()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,startswithv,email_parts,is_mail,vity_code,is_numeric
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,True,santhosh,True,VIJ,True
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,202,05-Feb-2024,False,raju,False,HYD,True
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,False,kiran,True,VI,True
3,Suresh Babu,suresh@outlook.com,GUNTUR,$1200,9871234567,404,22-Apr-2024,False,suresh,False,GUN,True
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,False,lakshmi,True,TIR,True

In [85]:
df["product_code"]=df["product_code"].str.removeprefix("PRD-")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,startswithv,email_parts,is_mail,vity_code,is_numeric
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,True,santhosh,True,VIJ,True
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,202,05-Feb-2024,False,raju,False,HYD,True
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,False,kiran,True,VI,True
3,Suresh Babu,suresh@outlook.com,GUNTUR,$1200,9871234567,404,22-Apr-2024,False,suresh,False,GUN,True
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,False,lakshmi,True,TIR,True