<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/String_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
# # string processing in pandas means perfroming operations on text(string)
# # data stored in dataframe columns using pandas string functions
# cHevuri
# 1000,
# 50
# chevurisanthosh@gmail.com
# chevurisantosh@outlook.com
# "    santosh"

In [113]:
s = "   lahari"
#if we want to remove spaces we will use strip method
#lstrip it will remove spaces in left side
#rstrip it will remove spaces in right side only
#strip #it will remove spaces from both sides
print(s.strip())

lahari

In [114]:
df = pd.read_csv("/content/drive/MyDrive/Datasets for datascience/string_processing_dataset.csv")

In [115]:
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,RAJU@YAHOO.COM,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [116]:
df["email"] = df["email"].str.lower() #we are converting into the lower case
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [117]:
#convert cities into uppercase
df["city"] = df["city"].str.upper()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [118]:
#converting customer_name column into title
df["customer_name"] = df["customer_name"].str.title()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,Kiran Reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,Suresh Babu,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [119]:
df["name_length"] = df["customer_name"].str.len()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024,19
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024,13
3,Suresh Babu,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024,13
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024,12

In [120]:
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024,19
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024,13
3,Suresh Babu,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024,13
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024,12

In [121]:
# regex = false tella pandas to treat the value as normal text and not as a special pattern

In [122]:
df["purchase_amount"] = df["purchase_amount"].str.replace("Rs ", "", regex= False)
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,kiran@gmail.com,VIZAG,"3,500",9988776655,PRD-303,18-Mar-2024,13
3,Suresh Babu,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024,13
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12

In [123]:
df["purchase_amount"] = df["purchase_amount"].str.replace("$", "", regex= False)
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,kiran@gmail.com,VIZAG,"3,500",9988776655,PRD-303,18-Mar-2024,13
3,Suresh Babu,suresh@outlook.com,GUNTUR,"1,200",9871234567,PRD-404,22-Apr-2024,13
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12

In [124]:
df["purchase_amount"] = df["purchase_amount"].str.replace(",", "", regex= False)
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12

In [125]:
df["is_mail"] = df["email"].str.contains("gmail")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length,is_mail
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,True
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,True
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,True

In [126]:
df["endswith"] = df["email"].str.endswith(".com")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length,is_mail,endswith
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,True,True
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,True
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,True,True
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,True
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,True,True

In [127]:
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length,is_mail,endswith
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,True,True
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,True
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,True,True
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,True
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,True,True

In [128]:
df["email_parts"] = df["email"].str.split("@")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length,is_mail,endswith,email_parts
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,True,True,"[santhosh, gmail.com]"
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,True,"[raju, yahoo.com]"
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,True,True,"[kiran, gmail.com]"
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,True,"[suresh, outlook.com]"
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,True,True,"[lakshmi, gmail.com]"

In [129]:
df["startswithv"] = df["city"].str.startswith("V")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length,is_mail,endswith,email_parts,startswithv
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,True,True,"[santhosh, gmail.com]",True
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,True,"[raju, yahoo.com]",False
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,True,True,"[kiran, gmail.com]",False
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,True,"[suresh, outlook.com]",False
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,True,True,"[lakshmi, gmail.com]",False

In [130]:
df["email_parts"] = df["email"].str.split("@").str[0]
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length,is_mail,endswith,email_parts,startswithv
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,True,True,santhosh,True
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,True,raju,False
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,True,True,kiran,False
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,True,suresh,False
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,True,True,lakshmi,False

In [131]:
df["vity_code"]=df["city"].str[:3]
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length,is_mail,endswith,email_parts,startswithv,vity_code
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,True,True,santhosh,True,VIJ
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,True,raju,False,HYD
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,True,True,kiran,False,VI
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,True,suresh,False,GUN
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,True,True,lakshmi,False,TIR

In [132]:
df["is_numeric"]=df["phone"].astype(str).str.isnumeric()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length,is_mail,endswith,email_parts,startswithv,vity_code,is_numeric
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,True,True,santhosh,True,VIJ,True
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,True,raju,False,HYD,True
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,True,True,kiran,False,VI,True
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,True,suresh,False,GUN,True
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,True,True,lakshmi,False,TIR,True

In [133]:
df["product_code"]=df["product_code"].str.removeprefix("PRD-")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length,is_mail,endswith,email_parts,startswithv,vity_code,is_numeric
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,True,True,santhosh,True,VIJ,True
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,True,raju,False,HYD,True
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,13,True,True,kiran,False,VI,True
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,True,suresh,False,GUN,True
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,12,True,True,lakshmi,False,TIR,True

Task

In [134]:
df = pd.read_csv("/content/drive/MyDrive/Datasets for datascience/bank_customer_data (1).csv")
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,SANthosh Chevuri,SANTHOSH@GMAIL.COM,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,RAJU kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,kiran REDDY,KIRAN@GMAIL.COM,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,SURESH BABU,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi devi,LAKSHMI@GMAIL.COM,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [135]:
df["customer_name"] = df["customer_name"].str.title()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,KIRAN@GMAIL.COM,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [ ]:
df["email"]=df["email"].str.lower()
df

In [ ]:
df["bank_name"]=df["bank_name"].str.upper()
df

In [ ]:
df["account_type"]=df["account_type"].str.upper()
df

In [ ]:
df['balance'] = df['balance'].str.replace('Rs', '', regex=False)
df['balance'] = df['balance'].str.replace('$', '', regex=False)
df['balance'] = df['balance'].str.replace(',', '', regex=False)
df['balance'] = df['balance'].str.strip()
df

In [ ]:
df["balance"]=df["balance"].astype(int)
df

In [ ]:
df["username"]=df["email"].str.split("@").str[0]
df

In [ ]:
df["domain"]=df["email"].str.split("@").str[1]
df

In [ ]:
df["branch_code"]=df["branch_city"].str[:3].str.upper()
df

In [ ]:

df['account_number'] = df['account_number'].str.replace('ACC-', '', regex=False)
df