<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/Time_Series_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Time Series Data**
    ---> Time Series Data is the data collected over time
    ---> example : stock price
    ---> in normal data row order is not important
    ---> in time series data we need particular data

In [4]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv("/content/drive/MyDrive/Datasets for datascience/stock_price_data.csv")
df

          Date  Stock_Price  Volume
0   2025-01-01        100.0  1000.0
1   2025-01-02        102.0  1200.0
2   2025-01-03        105.0  1500.0
3   2025-01-05          NaN  1400.0
4   2025-01-06        108.0     NaN
5   2025-01-08        112.0  1700.0
6   2025-01-09        110.0  1650.0
7   2025-01-10          NaN  1800.0
8   2025-01-12        118.0  2000.0
9   2025-01-13        121.0     NaN
10  2025-01-15        125.0  2200.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         11 non-null     object
 1   Stock_Price  9 non-null      float64
 2   Volume       9 non-null      float64
dtypes: float64(2), object(1)
memory usage: 396.0+ bytes

In [9]:
df.head()

         Date  Stock_Price  Volume
0  2025-01-01        100.0  1000.0
1  2025-01-02        102.0  1200.0
2  2025-01-03        105.0  1500.0
3  2025-01-05          NaN  1400.0
4  2025-01-06        108.0     NaN